language: java
jdk:
- oraclejdk8
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true
script: mvn test
after_success:
- mvn clean cobertura:cobertura coveralls:report
env:
  global:
    secure: zA5VMHDFKUBonr2kbfv157T/1vJteXf47rDmCcV29szz7QL+m3VPTTLSi6YlLWeE4Vrop5yKt8NAtSFjDSsnc0H6F2Rqtpw9w/JPM/cbGBHHUzfkR42rauTJ/1slnUCBvlvDvhSXJPeoX8iaYqoqluBl6QMnLggWIGxEaPDaVrcq7j37qixnlHG8jC2/R6QqCTBWqAjh+nqb1EEWynUFDIfZkQl4mCt4xPQNc8WCga7RB8k7RM6bdoLln6jRnnzxyd3bknAGww9u9xQH1w2n5hBSA7IfzZGgVWivgt7QOvP4dO9t942nVfZLrF0YyZoTPXP+Z0lG5KQxVsOLvZNEzah05Sme0TiNitiEX6q4qup1uBw/v5vtLrNtQZ/zF3BJtgewetbLAIyO17QapW8ioJTcUvjItFbek0VZjvl7o7L91PW+6sHFSDSR+SWhTVh7BRO1Bv8w6BTnw+W/Xxbm4D86Bv4pCReLCjXceqrVORYAeceLnujzNPyE+Pe7/rD+dd8DRX9mYUTS5U8S7DESaAJSaw+Sg48E2PDkdSxlTatz5mqLYVuQDXcNPW8ieLJXSdQxcEKRZ4Df0nkWiyWitCrgW2miEPdFot/rhv8SNIIe+eTnCZH14/3R8AXLG0dgnRmYZmvQqT8lwq96v9rOu8PzdE4M322I7tsttdD1GMA=
